name: Hello-World-Action
on: [push] # Trigger the workflow on push events

jobs: # Define the jobs to be run
  say-hello: # Job name
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions! Push event has occurred." # Command to execute